### ISSUE TITLE
复制相同id但lore不同的物品

### ISSUE THREAD

**Issue by balugaq** [SlimefunGuguProject/Networks#103]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/Networks/issues)，且没有找到相同的问题

### 问题描述

设置两个**粘液id相同**的物品的存储，推送器中要复制的物品放第一个（1.0E7），另一个与他有任意nbt不同的物品放后面（0）
复制完成

### 复现步骤

https://github.com/SlimefunGuguProject/Networks/assets/129668183/89a834e7-febc-461c-94af-05eb51f96ff2

### 预期行为

仅输入一个 1.0E7

### 服务器日志

无报错

### 错误报告

无报错

### 服务端软件

Purpur

### Minecraft 版本

1.19.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

Preview Build

Slimefun-Preview Build #859-c0870137.jar（github的action中下载）

### 插件版本

87

**Comment by balugaq** [comment]
预期行为 修正
仅输出 1 个 1.0E7， 64个 0

**Comment by ybw0014** [comment]
需要附属自行解决，物品类需要有 `DistinctiveItem`。
