### ISSUE TITLE
网格物品丢失

### ISSUE THREAD

**Issue by JWJUN233233** [SlimefunGuguProject/Networks#105]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/Networks/issues)，且没有找到相同的问题

### 问题描述

![image](https://github.com/SlimefunGuguProject/Networks/assets/66861021/580e755d-52d1-46d2-90c7-a6f2b2cab6d2)
当服务器重启后 网格最后一个物品丢失

### 复现步骤

1. 放入物品
2. /restart
3. 观察现象
4. 得出结论 当插件一定时 服务器重启会导致网格最后一个物品丢失

### 预期行为

物品不丢失

### 服务器日志

无

### 错误报告

无

### 服务端软件

Paper

### Minecraft 版本

1.19.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

![image](https://github.com/SlimefunGuguProject/Networks/assets/66861021/bc336010-753b-44cb-a7f6-3ec6bcaa33af)

### 插件版本

87

**Comment by JWJUN233233** [comment]
https://github.com/StarWishsama/Slimefun4/pull/855可修复

**Comment by ybw0014** [comment]
本体 PR 已合并
