### ISSUE TITLE
复制网络蓝图

### ISSUE THREAD

**Issue by balugaq** [SlimefunGuguProject/Networks#106]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [ ] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [ ] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/Networks/issues)，且没有找到相同的问题

### 问题描述

现在发现网络蓝图也有问题了（视频如下，尽管这影响并不大）#103 
![c6380adf3e24cf9a93d71b60873751b4](https://github.com/SlimefunGuguProject/Networks/assets/129668183/7861598f-3ff3-42c7-a7f8-5d835d3ed056)

https://github.com/SlimefunGuguProject/Networks/assets/129668183/55ad7968-66d4-45e4-b5ad-fe2ae2cd4824

### 复现步骤

#103 

### 预期行为

#103 

### 服务器日志

无

### 错误报告

无

### 服务端软件

Purpur

### Minecraft 版本

1.19.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

#103 

### 插件版本

91

**Comment by ybw0014** [comment]
emm，就为了省几个材料？

**Comment by balugaq** [comment]
省时间，因为编码机必须输出槽空了才能继续合成
