### ISSUE TITLE
拆除网络控制器后仍能继续使用网格

### ISSUE THREAD

**Issue by balugaq** [SlimefunGuguProject/Networks#109]
### 检查项目

- [X] 你使用的是从构建站下载的版本
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/Networks/issues)，且没有找到相同的问题

### 问题描述

拆除网络控制器后仍能继续使用网格，无论网格是否在控制器旁边（暂未测试出刷物）

### 复现步骤

https://github.com/SlimefunGuguProject/Networks/assets/129668183/d8a8a628-9103-40c8-ac70-81e771d02648

### 预期行为

网格中的内容应当被清空，并且不能继续使用

### 服务器日志

无

### 错误报告

无

### 服务端软件

Paper

### Minecraft 版本

1.20.2

### Slimefun版本

Preview Build （github自行构建的）

### 插件版本

92

**Comment by balugaq** [comment]
难以复现，暂时close

**Comment by ybw0014** [comment]
已经复现出来了，但是没空找原因

**Comment by balugaq** [comment]
那我先reopen，然后看看能不能找到问题吧
