### ISSUE TITLE
严重刷物bug

### ISSUE THREAD

**Issue by balugaq** [SlimefunGuguProject/Networks#117]
### 检查项目

- [X] 你使用的是从构建站下载的版本
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/Networks/issues)，且没有找到相同的问题

### 问题描述

如题

当两个控制器接触到一起时，并且其中一个被清除后，我称被清除的控制器的网络为被损坏网络

当网络单元在被损坏网络中被挖掉时，似乎并不会清除自身的粘液数据，当被损坏网络的网络控制器恢复后，网络单元正常运作

在恢复网络控制器前，我们挖掉网络单元并放上网格，此时网格就具备了存储物品和显示物品的功能，再放上网络控制器即可完成刷物。

不确定是否与 #109 有关

### 复现步骤

https://github.com/SlimefunGuguProject/Networks/assets/129668183/e5de9369-6470-447e-a477-0f13d1701923

### 预期行为

网络单元数据正常清除

### 服务器日志

无

### 错误报告

无

### 服务端软件

Purpur

### Minecraft 版本

1.20.4

### Slimefun版本

226af9b-Beta

### 插件版本

93

**Comment by lijinhong11** [comment]
逆天牢bug
