### ISSUE TITLE
疑似幽灵方块复活

### ISSUE THREAD

**Issue by balugaq** [SlimefunGuguProject/Networks#120]
### 检查项目

- [X] 你使用的是从构建站下载的版本
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/Networks/issues)，且没有找到相同的问题

### 问题描述

疑似幽灵方块复活
【低偶发】

### 复现步骤

https://github.com/user-attachments/assets/7f9a6311-f578-4f2d-aec7-b0d53b684da0

### 预期行为

【网络单元】的数据应该正常删除

### 服务器日志

无

### 错误报告

无

### 服务端软件

Purpur

### Minecraft 版本

1.20.1

### Slimefun版本

![3a2cb0ebbe51b3f3a06e5b4e20533a5a](https://github.com/user-attachments/assets/3dbcd3d4-8abb-4468-a4a6-91f6e35486e5)

### 插件版本

93

**Comment by balugaq** [comment]
粘液版本和网络版本都不是目前最新的【截止2024.7.14】，我不确定这是否会对结果造成影响，但从其中一个汉化版的fork来看（已确认过sync fork）仍然可以复现

**Comment by rakhabilly1** [comment]
what's ur discord

**Comment by balugaq** [comment]
May we should talk on https://github.com/Sefiraat/Networks/issues/192?

**Comment by balugaq** [comment]
Are you an upstream manager?

**Comment by balugaq** [comment]
My discord: mmmjjkx

**Comment by balugaq** [comment]
已修复
