### ISSUE TITLE
1.21无法从网格中取出带有效果的药水

### ISSUE THREAD

**Issue by CuteLittleSky** [SlimefunGuguProject/Networks#123]
### 检查项目

- [X] 你使用的是从构建站下载的版本
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/Networks/issues)，且没有找到相同的问题

### 问题描述

1.21无法从网格中取出带有效果的药水
测试了网格和推送器都不行

### 复现步骤

![recording](https://github.com/user-attachments/assets/7e88629f-ba36-4fd2-b79b-09c4235f4648)

### 预期行为

能取出来....

### 错误报告

https://paste.guizhanss.net/vZ6sX

### 服务端软件

Spigot

### Minecraft 版本

1.21

### Slimefun版本

a19da27-insider

### 插件版本

Build 98

**Comment by ybw0014** [comment]
和本体的这个issue原因是一样的（https://github.com/SlimefunGuguProject/Slimefun4/issues/933）需要等本体修复
