### ISSUE TITLE
无法加载bug

### ISSUE THREAD

**Issue by xinge4088** [SlimefunGuguProject/Networks#124]
### 检查项目

- [X] 你使用的是从构建站下载的版本
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/Networks/issues)，且没有找到相同的问题

### 问题描述

服务器崩溃之后，重启一直报错，下方是报错文本

### 复现步骤

1.Networks-Build 94 2.开启自动更新

### 预期行为

Networks-Build 100 不兼容，但是自动更新

### 服务器日志

https://paste.guizhanss.net/p0aJk

### 服务端软件

Paper

### Minecraft 版本

1.20.4

### Slimefun版本

slimefun-23.10.16

### 插件版本

Networks-Build 100 (git 672c505).jar

**Comment by ybw0014** [comment]
今天是2024年8月21日
