### ISSUE TITLE
网格吞掉物品

### ISSUE THREAD

**Issue by LaughingCatGGG** [SlimefunGuguProject/Networks#50]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [ ] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [x] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/Networks/issues)，且没有找到相同的问题

### 问题描述

网格在开启瞬间物品格子内为空气状态而不是玻璃，放入物品无法取出并在刷新后消失。

### 复现步骤

https://user-images.githubusercontent.com/105503680/170808359-a350299c-9cf9-44fc-bc47-37f903ad660b.mp4

### 预期行为

不可往格子内放入物品或提前加载

### 服务器日志

无

### 错误报告

五

### 服务端软件

Purpur

### Minecraft 版本

1.18.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

Slimefun 运行的服务器环境:\nPurpur git-Purpur-1446 (MC: 1.18.1)
Slimefun 2022.04-release\nMetrics-组件 #28 
Java 17\n\n由 StarWishsama 汉化
请不要将此版本信息截图到 Discord/Github 反馈 Bug
优先到汉化页面反馈\n\n安装的附属插件: (23)
Networks vBuild 50 zh-CN(ybw0014) (git 886d7e4)
DanceTree v1.0.0\n  DyedBackpacks vBuild 1 zh-CN(baoad) (git 823de85)  
ExtraTools vBuild 3 zh-CN(SlimefunGuguProject) (git 3e59783)\n  EDisable v1.0.0  
ElectricSpawnersFix v1.0.0\n  FoxyMachines vBuild 11 zh-CN(ybw0014) (git ccff8f3)  
SlimefunWarfare vBuild 6 zh-CN(ybw0014) (git 86735ae) 
DynaTech vBuild 24 zh-CN(ybw0014) (git ca7d8c6)\n  SfRecipeFix vall
ExoticGarden vBuild 4 zh-CN(ybw0014) (git b7cce7e) 
InfinityExpansion vTest 3 zh-CN(baoad) (git aa441d1)\n  CMILib v1.1.2.5
LiteXpansion vMODIFIED\n  ElectricSpawners vBuild 4 zh-CN(ybw0014) (git 0d7b9bb)
SfItemUseLimit v1.0.0\n  VillagerUtil vBuild 2 zh-CN(ybw0014) (git f019674)
SoulJars vBuild 6 zh-CN(ybw0014) (git 7c3d94e)
mcddwipe v1.0.0\n  SlimeTinker vBuild 32 zh-CN(ybw0014) (git 25590ea)
Galactifun vBuild 6 zh-CN(baoad) (git bece648)\n  FluffyMachines vBuild 4 zh-CN(baoad) (git 228b135)
CMI v9.1.4.1

### 插件版本

50

**Comment by ybw0014** [comment]
服务器tps多少啊，感觉是因为卡顿造成的

**Comment by LaughingCatGGG** [comment]
> 服务器tps多少啊，感觉是因为卡顿造成的

确实tps越低出现的时间越长，但是20tps时也会在重启后第一次打开网格时出现短暂的空格

**Comment by ybw0014** [comment]
玩家应避免在加载期间向界面内放入物品
