### ISSUE TITLE
“网络原版容器推送器”汉化问题

### ISSUE THREAD

**Issue by Annijang** [SlimefunGuguProject/Networks#63]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [ ] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [ ] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/Networks/issues)，且没有找到相同的问题

### 问题描述

没什么好说的，也就是多打了两个“推进”字，希望能在github上删除这个重复的字，谢谢
![image](https://user-images.githubusercontent.com/75552974/181042773-7165ff78-3a91-4cf3-9e22-198cba9ed711.png)

### 复现步骤

X

### 预期行为

X

### 服务端软件

Paper

### Minecraft 版本

1.18.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

2022.07

### 插件版本

X

**Comment by ybw0014** [comment]
4b1690b9a8bb8ac161be714a9477d6733334f071
