### ISSUE TITLE
[难以复现]网络与其他机器卡UI刷物品

### ISSUE THREAD

**Issue by LaughingCatGGG** [SlimefunGuguProject/Networks#66]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [ ] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [ ] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/Networks/issues)，且没有找到相同的问题

### 问题描述

当粘液机器A卡为原版方块无法打开ui时，挖掉这个方块并放置网络抓取器，两种机器的UI会重叠，并在A机器可以拿取的格子内可以取出抓取器UI的物品，若此物品为抓取器抓取的机器方块，此方块可作为机器放置。
同理，网络量子存储与其他箱子ui（如网络单元）重叠时，可拿出网络量子存储绑定的物品。

### 复现步骤

此BUG涉及到机器变为原版这个远古BUG，难以复现
等待粘液机器变为原版
挖掉坏掉的机器方块
放置其他机器方块
UI重叠
图片为食品加工机与网络抓取器UI重叠
![图片](https://user-images.githubusercontent.com/105503680/187056538-b87f6dac-be1f-4003-b4a0-da65119bdd3b.png)

### 预期行为

若从源头修复（机器卡为原版方块）最好。
若暂无法修复，可尝试将无法拿取的UI物品设置一个NBT使其不能通过机器与玩家背包。

### 服务端软件

Purpur

### Minecraft 版本

1.19.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

Slimefun 运行的服务器环境:
Purpur git-Purpur-1735 (MC: 1.19)
Slimefun cf19487-canary
Metrics-组件 #28
Java 17

由 StarWishsama 汉化
请不要将此版本信息截图到 Discord/Github 反馈 Bug
优先到汉化页面反馈

安装的附属插件: (29)
  Networks vBuild 64 zh-CN(ybw0014) (git c783ccd)
  DanceTree v1.0.1
  CrystamaeHistoria vBuild 27 zh-CN(SlimefunGuguProject) (git 5baf82f)
  ExtraTools vBuild 5 zh-CN(SlimefunGuguProject) (git 7d520b7)
  FoxyMachines vBuild 11 zh-CN(ybw0014) (git ccff8f3)
  DynaTech vBuild 32 zh-CN(ybw0014) (git 6eafea4)
  ItemRepo v1.0.0
  BedrockTechnology v1.0-beta-220706f0
  CMILib v1.2.3.3
  InfinityExpansion vBuild 2 zh-CN(SlimefunGuguProject) (git bec2020)
  ElectricSpawners vBuild 4 zh-CN(ybw0014) (git 0d7b9bb)
  SfItemUseLimit v1.0.0
  VillagerUtil vBuild 2 zh-CN(ybw0014) (git f019674)
  KD v1.0.0
  SlimyTreeTaps vBuild 2 zh-CN(ybw0014) (git 8a58b9f)
  mcddwipe v1.0.0
  SlimeTinker vBuild 41 zh-CN(ybw0014) (git 33334b4)
  FluffyMachines vBuild 6 zh-CN(baoad) (git be02db6)
  CMI v9.2.3.1
  DyedBackpacks vBuild 2 zh-CN(baoad) (git 3a17d71)
  ElectricSpawnersFix v1.0.0
  SlimefunBlockPlaceLimit v1.0.0
  SoundMuffler vBuild 1 zh-CN(baoad) (git b1678a8)
  SlimefunLuckyBlocks vBuild 1 zh-CN(baoad) (git d435fa3)
  ExoticGarden vBuild 10 zh-CN(ybw0014) (git 4a9d091)
  FinalTECH vBuild 19 zh-CN(ECRO) (git 5a5fe76)
  LiteXpansion vBuild 20 zh-CN(ybw0014) (git 785da3d)
  SoulJars vBuild 8 zh-CN(ybw0014) (git 23eb7a7)
  PotionExpansion vBuild 1 zh-CN(baoad) (git b25bd1d)

### 插件版本

64

**Comment by ybw0014** [comment]
粘液存储系统的特性，得等114514年后粘液的存储系统重写才有可能解决
