### ISSUE TITLE
网格（带合成）问题 paper1.20.1

### ISSUE THREAD

**Issue by anxge** [SlimefunGuguProject/Networks#89]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/Networks/issues)，且没有找到相同的问题

### 问题描述

工作台图标下面出成品的那一格
![E2AF76DA205DC8455AF5AE03CE489A9C](https://github.com/SlimefunGuguProject/Networks/assets/123163148/e34a72dd-cbd8-46a4-98f9-f890190aa116)
如果下面的东西一组了
还会消耗物品但是不给合成物品

### 复现步骤

放入材料
合成

### 预期行为

正常出成品

### 服务端软件

Spigot

### Minecraft 版本

1.19.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

![image](https://github.com/SlimefunGuguProject/Networks/assets/123163148/4620d9bc-ac41-4354-a82f-4e09b91aadb8)

### 插件版本

78

**Comment by ybw0014** [comment]
未复现成功
