### ISSUE TITLE
绑定后的网络远程访问器跨服后失效

### ISSUE THREAD

**Issue by Meawerful** [SlimefunGuguProject/Networks#94]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/Networks/issues)，且没有找到相同的问题

### 问题描述

我那边是个世界分服的生存服，终极网络远程访问器在其中一个世界（服务器）绑定后，玩家拿着它到另一个世界（服务器）后它就会失效，像普通的展示框一样可以被放下来了。我检验过跨服前后的访问器的物品，它的nbt并没有随跨服发生变化。

### 复现步骤

拿终极网络远程访问器绑定网络后跨服即可

### 预期行为

我觉得跨服也应该让它保持是粘液物品，最好还能跨服访问网络

### 服务器日志

https://paste.guizhanss.net/aibaI

### 服务端软件

Paper

### Minecraft 版本

1.19.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

![IOC~6MQJ@9JP~Z)N%$QA~F2](https://github.com/SlimefunGuguProject/Networks/assets/65216549/3c14276f-4891-4119-8962-85ec50e51aba)

### 插件版本

0a0715a-Insider

**Comment by ybw0014** [comment]
暂时不支持跨服
