### ISSUE TITLE
网络正常加载但无法使用

### ISSUE THREAD

**Issue by littlecofo** [SlimefunGuguProject/Networks#97]
### 检查项目

- [X] 你使用的是从构建站下载的版本 (https://builds.guizhanss.net)
- [X] 你已经检验过下载的文件的校验和，确认已完整下载文件 (暂未推出)
- [X] 你没有对下载的文件内容进行任何更改
- [X] 你没有安装`CS-CoreLib`
- [X] 你已经寻找过[已知问题列表](https://github.com/SlimefunGuguProject/Networks/issues)，且没有找到相同的问题

### 问题描述

当我放置“网络推进器”，“网络入口”等网络方块时，过几秒网络方块便会消失，后台出现报错。

### 复现步骤

放置网络方块

### 预期行为

正常使用

### 服务器日志

https://pastebin.com/9V92frsd

### 错误报告

https://paste.guizhanss.net/OaTFn

### 服务端软件

Spigot

### Minecraft 版本

1.18.x

### CS-CoreLib 版本

- [X] 我没有安装CS-CoreLib

### Slimefun版本

Paper git-Paper-387 (MC: 1.18.2)
Slimefun 2022.06-release
Metrics-组件 #28
Java 17

### 插件版本

vBuild 85 (git 2e809b2)

**Comment by ybw0014** [comment]
粘液本体太旧了
